set_target_properties(${CMAKE_PROJECT_NAME}
    PROPERTIES OUTPUT_NAME ${BIN_OUTPUT_NAME})

install(TARGETS ${CMAKE_PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_PREFIX})

add_custom_command(
    OUTPUT              ${CMAKE_INSTALL_PREFIX}/${CMAKE_PROJECT_NAME}${CMAKE_EXECUTABLE_SUFFIX}
    DEPENDS             ${CMAKE_PROJECT_NAME}
    WORKING_DIRECTORY   ${CMAKE_SOURCE_DIR}
    COMMAND             ${CMAKE_COMMAND} -E create_symlink
    ARGS                ${BIN_OUTPUT_NAME}${CMAKE_EXECUTABLE_SUFFIX}
                        ${CMAKE_INSTALL_PREFIX}/${CMAKE_PROJECT_NAME}${CMAKE_EXECUTABLE_SUFFIX})

add_custom_command(
    TARGET ${CMAKE_PROJECT_NAME} POST_BUILD
    DEPENDS           ${CMAKE_INSTALL_PREFIX}/${CMAKE_PROJECT_NAME}${CMAKE_EXECUTABLE_SUFFIX}
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    COMMAND $<TARGET_FILE:${CMAKE_PROJECT_NAME}> ${INI}
)
